import type { Metadata } from 'next';
import { Ubuntu } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { ThemeProvider } from '@/components/theme-provider';

const ubuntu = Ubuntu({ weight: ['300','400', '500', '700'], subsets: ['latin' ]});

export const metadata: Metadata = {
  title: 'LMS-Launchpad',
  description: 'Generated by LMS-Launchpad',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange> 
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
